export { AddCentre } from '@components/pages/centre/add-center';
export { AddDomain } from '@components/pages/domain/add-domain';
export { default as CentrePage } from '@components/pages/centre';
export { default as DomainPage } from '@components/pages/domain';
export { default as CenterDomainPage } from '@components/pages/centre/domain';
export { AddCentreDomain } from '@components/pages/centre/domain/add-center-domain';
export { CenterPageComponents } from '@components/pages/centre/center';
export { default as StaffPage } from '@components/pages/staff';
export { default as ProjectsPage } from '@components/pages/projects';
export { AddProjects } from '@components/pages/projects/add-projects';
export { default as BatchPage } from '@components/pages/batch';
export { AddBatch } from '@components/pages/batch/add-batch';
export { StudentPersonalDetailsForm } from '@pages/students-registration/student-personal-detail-form';
export { StudentPresentAddressForm } from '@pages/students-registration/student-present-address-form';
export { StudentPermanentAddressForm } from '@pages/students-registration/student-permanent-address-form';
export { StudentOtherInfoForm } from '@pages/students-registration/student-other-info-form';
export { StudentParentDetailsForm } from '@pages/students-registration/student-parents-detail-form';
export { StudentRegistrationForm } from '@pages/students-registration/student-registration-form';
